In [1]:
import pandas as pd
import numpy as np
import re
import glob

In [2]:
ls data/

Nmip_Day_100.txt* Nmip_Day_111.txt* Nmip_Day_122.txt* Nmip_Day_88.txt*
Nmip_Day_101.txt* Nmip_Day_112.txt* Nmip_Day_123.txt* Nmip_Day_90.txt*
Nmip_Day_102.txt* Nmip_Day_113.txt* Nmip_Day_124.txt* Nmip_Day_91.txt*
Nmip_Day_103.txt* Nmip_Day_114.txt* Nmip_Day_125.txt* Nmip_Day_92.txt*
Nmip_Day_104.txt* Nmip_Day_115.txt* Nmip_Day_126.txt* Nmip_Day_93.txt*
Nmip_Day_105.txt* Nmip_Day_116.txt* Nmip_Day_127.txt* Nmip_Day_94.txt*
Nmip_Day_106.txt* Nmip_Day_117.txt* Nmip_Day_128.txt* Nmip_Day_95.txt*
Nmip_Day_107.txt* Nmip_Day_118.txt* Nmip_Day_129.txt* Nmip_Day_96.txt*
Nmip_Day_108.txt* Nmip_Day_119.txt* Nmip_Day_84.txt*  Nmip_Day_97.txt*
Nmip_Day_109.txt* Nmip_Day_120.txt* Nmip_Day_85.txt*  Nmip_Day_98.txt*
Nmip_Day_110.txt* Nmip_Day_121.txt* Nmip_Day_86.txt*  Nmip_Day_99.txt*

In [3]:
mip = pd.read_csv('data/Nmip_Day_84.txt', sep='\t',index_col=None,header=None)
mip = mip.rename(columns={0:'day',1:'ew',2:'pp',3:'tt',4:'mip'})
mip.set_index(['ew','pp','tt','day'],inplace=True)
mip = mip.unstack(3)
mip.head()

                 mip
day               84
ew pp tt
0  1  1   145.289855
      2   144.240605
      3   144.925187
      4   157.738906
      5   161.875796

In [4]:
f_names=glob.glob("data/*.txt")
#f_names = np.array(f_names)
print('length',len(f_names))
f_names[0:5]

length 44

['data/Nmip_Day_115.txt',
 'data/Nmip_Day_101.txt',
 'data/Nmip_Day_129.txt',
 'data/Nmip_Day_128.txt',
 'data/Nmip_Day_100.txt']

In [5]:
def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    '''
        http://nedbatchelder.com/blog/200712/human_sorting.html
    '''
    return [ atoi(c) for c in re.split('(\d+)', text) ]

In [6]:
f_names.sort(key=natural_keys)
f_names[0:5]

['data/Nmip_Day_84.txt',
 'data/Nmip_Day_85.txt',
 'data/Nmip_Day_86.txt',
 'data/Nmip_Day_88.txt',
 'data/Nmip_Day_90.txt']

In [7]:
f_names = f_names[1:]

In [8]:
for f in f_names:
    df = pd.read_csv(f, sep='\t',index_col=None,header=None)
    df = df.rename(columns={0:'day',1:'ew',2:'pp',3:'tt',4:'mip'})
    df.set_index(['ew','pp','tt','day'],inplace=True)
    df = df.unstack(3)
    mip = mip.merge(df,how='outer',on=['ew','pp','tt'])

In [25]:
mip.tail(10)

                 mip                                                  \
day              84          85          86          88          90
ew pp tt
1  12 22  117.924217  117.924217  117.924217  117.924217  117.924217
      23  116.616845  116.616845  116.616845  116.616845  116.616845
      24  118.537340  118.537340  118.537340  118.537340  118.537340
      25  116.897942  116.897942  116.897942  116.897942  116.897942
      26  117.768589  117.768589  117.768589  117.768589  117.768589
      27  117.563522  117.563522  117.563522  117.563522  117.563522
      28  116.245080  116.245080  116.245080  116.245080  116.245080
      29  118.141423  118.141423  118.141423  118.141423  118.141423
      30  116.562848  116.562848  116.562848  116.562848  116.562848
      31  116.295114  116.295114  116.295114  116.295114  116.295114

                                                                      \
day              91          92          93          94          95
ew pp tt
1  12 22  117.924217  117.924217  117.924217  117.924217  117.924217
      23  116.616845  116.616845  116.616845  116.616845  116.616845
      24  118.537340  118.537340  118.537340  118.537340  118.537340
      25  116.897942  116.897942  116.897942  116.897942  116.897942
      26  117.768589  117.768589  117.768589  117.768589  117.768589
      27  117.563522  117.563522  117.563522  117.563522  117.563522
      28  116.245080  116.245080  116.245080  116.245080  116.245080
      29  118.141423  118.141423  118.141423  118.141423  118.141423
      30  116.562848  116.562848  116.562848  116.562848  116.562848
      31  116.295114  116.295114  116.295114  116.295114  116.295114

             ...                                                      \
day          ...             120         121         122         123
ew pp tt     ...
1  12 22     ...      117.924217  117.924217  117.924217  117.924217
      23     ...      116.616845  116.616845  116.616845  116.616845
      24     ...      118.537340  118.537340  118.537340  118.537340
      25     ...      116.897942  116.897942  116.897942  116.897942
      26     ...      117.768589  117.768589  117.768589  117.768589
      27     ...      117.563522  117.563522  117.563522  117.563522
      28     ...      116.245080  116.245080  116.245080  116.245080
      29     ...      118.141423  118.141423  118.141423  118.141423
      30     ...      116.562848  116.562848  116.562848  116.562848
      31     ...      116.295114  116.295114  116.295114  116.295114

                                                                      \
day              124         125         126         127         128
ew pp tt
1  12 22  117.924217  117.924217  117.924217  117.924217  117.924217
      23  116.616845  116.616845  116.616845  116.616845  116.616845
      24  118.537340  118.537340  118.537340  118.537340  118.537340
      25  116.897942  116.897942  116.897942  116.897942  116.897942
      26  117.768589  117.768589  117.768589  117.768589  117.768589
      27  117.563522  117.563522  117.563522  117.563522  117.563522
      28  116.245080  116.245080  116.245080  116.245080  116.245080
      29  118.141423  118.141423  118.141423  118.141423  118.141423
      30  116.562848  116.562848  116.562848  116.562848  116.562848
      31  116.295114  116.295114  116.295114  116.295114  116.295114


day              129
ew pp tt
1  12 22  117.924217
      23  116.616845
      24  118.537340
      25  116.897942
      26  117.768589
      27  117.563522
      28  116.245080
      29  118.141423
      30  116.562848
      31  116.295114

[10 rows x 44 columns]

In [33]:
mip.columns

MultiIndex(levels=[['mip', 'ew', 'pp', 'tt'], [84, 85, 86, 88, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, '']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]],
           names=[None, 'day'])